
[versions]
activityKtx = "1.12.0"
annotation = "1.9.1"
appcompat = "1.7.1"
cardview = "1.0.0"
constraintlayout = "2.2.1"
coreKtx = "1.17.0"
coreSplashscreen = "1.2.0"
customQrGenerator = "2.0.0-alpha01"
datastorePreferences = "1.2.0"
edittextPicker = "2.1.1"
fragmentKtx = "1.8.9"
gridlayout = "1.1.0"
hiltAndroid = "2.57.2"
hiltCommon = "1.3.0"
jsoup = "1.21.2"
kavehcolorpicker = "v1.2.1"
kotlinxSerializationJson = "1.9.0"
lifecycleViewmodelKtx = "2.10.0"
material = "1.14.0-alpha07"
navigationFragmentKtx = "2.9.6"
okhttpUrlconnection = "5.3.2"
okio = "3.16.4"
okioVersion = "3.16.2"
paletteKtx = "1.0.0"
picasso = "2.71828"
recyclerview = "1.4.0"
retrofit = "3.0.0"
shapemorphview = "0.0.4"
transitionKtx = "1.6.0"
workRuntimeKtx = "2.11.0"

[libraries]
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
custom-qr-generator = { module = "com.github.alexzhirkevich:custom-qr-generator", version.ref = "customQrGenerator" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastorePreferences" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
edittext-picker = { module = "com.github.AliAzaz:Edittext-Picker", version.ref = "edittextPicker" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "hiltCommon" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kavehcolorpicker = { module = "com.github.Mohammad3125:KavehColorPicker", version.ref = "kavehcolorpicker" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpUrlconnection" }
material = { module = "com.google.android.material:material", version.ref = "material" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpUrlconnection" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttpUrlconnection" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-v3162 = { module = "com.squareup.okio:okio", version.ref = "okioVersion" }
palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
shapemorphview = { module = "io.github.dertefter:shapemorphview", version.ref = "shapemorphview" }
transition-ktx = { module = "androidx.transition:transition-ktx", version.ref = "transitionKtx" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }

[plugins]
